version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "build(deps)"
    labels:
      - dependencies
    groups:
      caddy:
        patterns:
          - "caddy"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci(deps)"
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"